export const countryFlagIcons = {
  AUS: '/assets/images/countryFlagIcons/AUS.png',
  AUT: '/assets/images/countryFlagIcons/AUT.png',
  AZE: '/assets/images/countryFlagIcons/AZE.png',
  BEL: '/assets/images/countryFlagIcons/BEL.png',
  BRA: '/assets/images/countryFlagIcons/BRA.png',
  BRN: '/assets/images/countryFlagIcons/BRN.png',
  CAN: '/assets/images/countryFlagIcons/CAN.png',
  CHN: '/assets/images/countryFlagIcons/CHN.png',
  DEU: '/assets/images/countryFlagIcons/DEU.png',
  ESP: '/assets/images/countryFlagIcons/ESP.png',
  FRA: '/assets/images/countryFlagIcons/FRA.png',
  GBR: '/assets/images/countryFlagIcons/GBR.png',
  HUN: '/assets/images/countryFlagIcons/HUN.png',
  ITA: '/assets/images/countryFlagIcons/ITA.png',
  JPN: '/assets/images/countryFlagIcons/JPN.png',
  KSA: '/assets/images/countryFlagIcons/KSA.png',
  MEX: '/assets/images/countryFlagIcons/MEX.png',
  MON: '/assets/images/countryFlagIcons/MON.png',
  NED: '/assets/images/countryFlagIcons/NED.png',
  NZL: '/assets/images/countryFlagIcons/NZL.png',
  QAT: '/assets/images/countryFlagIcons/QAT.png',
  SGP: '/assets/images/countryFlagIcons/SGP.png',
  THA: '/assets/images/countryFlagIcons/THA.png',
  UAE: '/assets/images/countryFlagIcons/UAE.png',
  USA: '/assets/images/countryFlagIcons/USA.png',
};
