export const driverIcons = {
  ALB: {
    halfBody: '/assets/images/drivers/halfBody/ALB.png',
    headshot: '/assets/images/drivers/headshot/ALB.png',
    helmet: '/assets/images/drivers/helmet/ALB.png',
    numberIcon: '/assets/images/drivers/numberIcon/ALB.png',
    profile: '/assets/images/drivers/profile/ALB.png',
  },
  ALO: {
    halfBody: '/assets/images/drivers/halfBody/ALO.png',
    headshot: '/assets/images/drivers/headshot/ALO.png',
    helmet: '/assets/images/drivers/helmet/ALO.png',
    numberIcon: '/assets/images/drivers/numberIcon/ALO.png',
    profile: '/assets/images/drivers/profile/ALO.png',
  },
  ANT: {
    halfBody: '/assets/images/drivers/halfBody/ANT.png',
    headshot: '/assets/images/drivers/headshot/ANT.png',
    helmet: '/assets/images/drivers/helmet/ANT.png',
    numberIcon: '/assets/images/drivers/numberIcon/ANT.png',
    profile: '/assets/images/drivers/profile/ANT.png',
  },
  BEA: {
    halfBody: '/assets/images/drivers/halfBody/BEA.png',
    headshot: '/assets/images/drivers/headshot/BEA.png',
    helmet: '/assets/images/drivers/helmet/BEA.png',
    numberIcon: '/assets/images/drivers/numberIcon/BEA.png',
    profile: '/assets/images/drivers/profile/BEA.png',
  },
  BOR: {
    halfBody: '/assets/images/drivers/halfBody/BOR.png',
    headshot: '/assets/images/drivers/headshot/BOR.png',
    helmet: '/assets/images/drivers/helmet/BOR.png',
    numberIcon: '/assets/images/drivers/numberIcon/BOR.png',
    profile: '/assets/images/drivers/profile/BOR.png',
  },
  DOO: {
    halfBody: '/assets/images/drivers/halfBody/DOO.png',
    headshot: '/assets/images/drivers/headshot/DOO.png',
    helmet: '/assets/images/drivers/helmet/DOO.png',
    numberIcon: '/assets/images/drivers/numberIcon/DOO.png',
    profile: '/assets/images/drivers/profile/DOO.png',
  },
  GAS: {
    halfBody: '/assets/images/drivers/halfBody/GAS.png',
    headshot: '/assets/images/drivers/headshot/GAS.png',
    helmet: '/assets/images/drivers/helmet/GAS.png',
    numberIcon: '/assets/images/drivers/numberIcon/GAS.png',
    profile: '/assets/images/drivers/profile/GAS.png',
  },
  HAD: {
    halfBody: '/assets/images/drivers/halfBody/HAD.png',
    headshot: '/assets/images/drivers/headshot/HAD.png',
    helmet: '/assets/images/drivers/helmet/HAD.png',
    numberIcon: '/assets/images/drivers/numberIcon/HAD.png',
    profile: '/assets/images/drivers/profile/HAD.png',
  },
  HAM: {
    halfBody: '/assets/images/drivers/halfBody/HAM.png',
    headshot: '/assets/images/drivers/headshot/HAM.png',
    helmet: '/assets/images/drivers/helmet/HAM.png',
    numberIcon: '/assets/images/drivers/numberIcon/HAM.png',
    profile: '/assets/images/drivers/profile/HAM.png',
  },
  HUL: {
    halfBody: '/assets/images/drivers/halfBody/HUL.png',
    headshot: '/assets/images/drivers/headshot/HUL.png',
    helmet: '/assets/images/drivers/helmet/HUL.png',
    numberIcon: '/assets/images/drivers/numberIcon/HUL.png',
    profile: '/assets/images/drivers/profile/HUL.png',
  },
  LAW: {
    halfBody: '/assets/images/drivers/halfBody/LAW.png',
    headshot: '/assets/images/drivers/headshot/LAW.png',
    helmet: '/assets/images/drivers/helmet/LAW.png',
    numberIcon: '/assets/images/drivers/numberIcon/LAW.png',
    profile: '/assets/images/drivers/profile/LAW.png',
  },
  LEC: {
    halfBody: '/assets/images/drivers/halfBody/LEC.png',
    headshot: '/assets/images/drivers/headshot/LEC.png',
    helmet: '/assets/images/drivers/helmet/LEC.png',
    numberIcon: '/assets/images/drivers/numberIcon/LEC.png',
    profile: '/assets/images/drivers/profile/LEC.png',
  },
  NOR: {
    halfBody: '/assets/images/drivers/halfBody/NOR.png',
    headshot: '/assets/images/drivers/headshot/NOR.png',
    helmet: '/assets/images/drivers/helmet/NOR.png',
    numberIcon: '/assets/images/drivers/numberIcon/NOR.png',
    profile: '/assets/images/drivers/profile/NOR.png',
  },
  OCO: {
    halfBody: '/assets/images/drivers/halfBody/OCO.png',
    headshot: '/assets/images/drivers/headshot/OCO.png',
    helmet: '/assets/images/drivers/helmet/OCO.png',
    numberIcon: '/assets/images/drivers/numberIcon/OCO.png',
    profile: '/assets/images/drivers/profile/OCO.png',
  },
  PIA: {
    halfBody: '/assets/images/drivers/halfBody/PIA.png',
    headshot: '/assets/images/drivers/headshot/PIA.png',
    helmet: '/assets/images/drivers/helmet/PIA.png',
    numberIcon: '/assets/images/drivers/numberIcon/PIA.png',
    profile: '/assets/images/drivers/profile/PIA.png',
  },
  RUS: {
    halfBody: '/assets/images/drivers/halfBody/RUS.png',
    headshot: '/assets/images/drivers/headshot/RUS.png',
    helmet: '/assets/images/drivers/helmet/RUS.png',
    numberIcon: '/assets/images/drivers/numberIcon/RUS.png',
    profile: '/assets/images/drivers/profile/RUS.png',
  },
  SAI: {
    halfBody: '/assets/images/drivers/halfBody/SAI.png',
    headshot: '/assets/images/drivers/headshot/SAI.png',
    helmet: '/assets/images/drivers/helmet/SAI.png',
    numberIcon: '/assets/images/drivers/numberIcon/SAI.png',
    profile: '/assets/images/drivers/profile/SAI.png',
  },
  STR: {
    halfBody: '/assets/images/drivers/halfBody/STR.png',
    headshot: '/assets/images/drivers/headshot/STR.png',
    helmet: '/assets/images/drivers/helmet/STR.png',
    numberIcon: '/assets/images/drivers/numberIcon/STR.png',
    profile: '/assets/images/drivers/profile/STR.png',
  },
  TSU: {
    halfBody: '/assets/images/drivers/halfBody/TSU.png',
    headshot: '/assets/images/drivers/headshot/TSU.png',
    helmet: '/assets/images/drivers/helmet/TSU.png',
    numberIcon: '/assets/images/drivers/numberIcon/TSU.png',
    profile: '/assets/images/drivers/profile/TSU.png',
  },
  VER: {
    halfBody: '/assets/images/drivers/halfBody/VER.png',
    headshot: '/assets/images/drivers/headshot/VER.png',
    helmet: '/assets/images/drivers/helmet/VER.png',
    numberIcon: '/assets/images/drivers/numberIcon/VER.png',
    profile: '/assets/images/drivers/profile/VER.png',
  },
};
